#!/usr/bin/env bash
# install-wrappers.sh — Install PATH wrappers that route install-adjacent
# npm/pnpm commands through Socket Firewall (sfw).
#
# WHY wrappers instead of shell aliases:
#   Shell aliases only fire in INTERACTIVE shells. Non-interactive subprocesses
#   bypass them entirely — that includes agent shell tools, scripts run via
#   `bash script.sh`, Makefiles, and `npm run` lifecycle scripts. PATH
#   wrappers fire for every invocation regardless of shell type, so this is
#   the right approach for any user whose installs are sometimes driven by
#   AI agents or scripts.
#
# WHY smart pass-through (only wrap install-adjacent commands):
#   sfw adds startup overhead per call. For non-install commands like
#   `npm --version`, `npm config get`, and `npm run`, that overhead is wasted —
#   those commands don't fetch packages so there's nothing to scan. The wrapper
#   checks the subcommand and only invokes sfw for fetch-adjacent ones.
#
# Usage:
#   install-wrappers.sh [MANAGER...]
#     MANAGER  Space-separated list of managers to wrap. Default: npm pnpm.
#              Supported: npm, pnpm. NOT bun — Bun scanner protection is
#              project-config-based (a different mechanism).
#
# Output: wrapper scripts written to ~/.local/bin/ (preferred) or ~/bin/.

set -euo pipefail

# Pick the wrapper directory. Prefer ~/.local/bin (XDG-standard, in PATH on
# macOS + most Linux distros by default). Fall back to ~/bin if that's the
# only one in PATH. If neither is in PATH, default to ~/.local/bin and ask
# the user to add it.
WRAPPER_DIR=""
NEED_PATH_SHIM=0
for candidate in "$HOME/.local/bin" "$HOME/bin"; do
  if [[ -d "$candidate" ]] || mkdir -p "$candidate" 2>/dev/null; then
    if echo "$PATH" | tr ':' '\n' | grep -qFx "$candidate"; then
      WRAPPER_DIR="$candidate"
      break
    fi
  fi
done
if [[ -z "$WRAPPER_DIR" ]]; then
  WRAPPER_DIR="$HOME/.local/bin"
  mkdir -p "$WRAPPER_DIR"
  NEED_PATH_SHIM=1
fi

# Sanity: sfw must be installed and on PATH
if ! command -v sfw >/dev/null 2>&1; then
  echo "ERROR: sfw not found. Install with: npm i -g sfw" >&2
  exit 3
fi

# Default to wrapping npm and pnpm
MANAGERS=("$@")
[[ ${#MANAGERS[@]} -eq 0 ]] && MANAGERS=(npm pnpm)

# Resolve the real binary path for a manager, skipping our wrapper dir and any
# existing socket-audit wrapper. This handles Homebrew, system installs, Volta,
# asdf, fnm, Corepack shims, and other PATH-managed setups.
detect_real() {
  local mgr="$1"
  local dir candidate old_ifs

  old_ifs="$IFS"
  IFS=:
  for dir in $PATH; do
    [[ -n "$dir" ]] || dir="."
    candidate="$dir/$mgr"
    [[ "$candidate" != "$WRAPPER_DIR/$mgr" ]] || continue
    [[ -x "$candidate" ]] || continue
    if ! grep -q "socket-audit-wrapper" "$candidate" 2>/dev/null; then
      echo "$candidate"
      IFS="$old_ifs"
      return 0
    fi
  done
  IFS="$old_ifs"

  for candidate in "/opt/homebrew/bin/$mgr" "/usr/local/bin/$mgr" "/usr/bin/$mgr"; do
    if [[ -x "$candidate" && "$candidate" != "$WRAPPER_DIR/$mgr" ]] &&
       ! grep -q "socket-audit-wrapper" "$candidate" 2>/dev/null; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

write_wrapper() {
  local mgr="$1"
  local real
  real=$(detect_real "$mgr") || { echo "  ✗ $mgr — not found on PATH, skipping" >&2; return 1; }
  local wrapper="$WRAPPER_DIR/$mgr"

  if [[ -L "$wrapper" ]]; then
    echo "  ✗ $wrapper is a symbolic link; leaving it untouched" >&2
    echo "    Resolve it manually or choose a different wrapper directory before retrying." >&2
    return 1
  fi

  if [[ -e "$wrapper" ]] && ! grep -q "socket-audit-wrapper" "$wrapper" 2>/dev/null; then
    echo "  ✗ $wrapper already exists and is not a socket-audit wrapper; leaving it untouched" >&2
    echo "    Move it aside or choose a different wrapper directory before retrying." >&2
    return 1
  fi

  # Which subcommands fetch packages (and so warrant sfw scanning)?
  local install_cmds
  case "$mgr" in
    npm)  install_cmds="install|i|in|isntall|add|update|up|upd|upgrade|ci|rebuild|rb|exec|x" ;;
    pnpm) install_cmds="install|i|add|update|up|upgrade|ci|rebuild|exec|dlx" ;;
    *)    echo "  ✗ Unknown manager: $mgr" >&2; return 1 ;;
  esac

  local tmp
  tmp="$(mktemp "$WRAPPER_DIR/.socket-audit-$mgr.XXXXXX")"
  cat > "$tmp" <<EOF
#!/usr/bin/env bash
# Socket Firewall wrapper for $mgr.
# Routes install-adjacent commands through sfw; pass-through everything else.
# Generated by socket-audit skill.
# Marker: socket-audit-wrapper
# To undo this one wrapper: rm "$wrapper"
# To undo all socket-audit Workflow B changes: bash <skill-dir>/scripts/uninstall.sh

set -e

REAL_BIN="$real"
if [ ! -x "\$REAL_BIN" ]; then
  echo "socket-audit wrapper: real $mgr not found at \$REAL_BIN" >&2
  exit 127
fi

case "\${1:-}" in
  $install_cmds)
    exec sfw "\$REAL_BIN" "\$@"
    ;;
  *)
    exec "\$REAL_BIN" "\$@"
    ;;
esac
EOF
  chmod +x "$tmp"
  mv "$tmp" "$wrapper"
  echo "  ✓ $wrapper -> $real (install commands route through sfw)"
}

echo "Installing wrappers in $WRAPPER_DIR..."
FAILED=0
for mgr in "${MANAGERS[@]}"; do
  if ! write_wrapper "$mgr"; then
    FAILED=1
  fi
done

if [[ "$NEED_PATH_SHIM" = "1" ]]; then
  cat <<EOF

⚠ $WRAPPER_DIR is not currently in your PATH. Add this to ~/.zshenv (or
~/.bashrc on bash-based shells):

  # Added by socket-audit skill.
  export PATH="$WRAPPER_DIR:\$PATH"

After that, open a new terminal so the change takes effect.
EOF
fi

if [[ "$FAILED" = "1" ]]; then
  echo
  echo "One or more wrappers were not installed. Review the messages above before claiming protection is active." >&2
  exit 1
fi

echo
echo "Verify with:"
for mgr in "${MANAGERS[@]}"; do
  echo "  command -v $mgr   # should print: $WRAPPER_DIR/$mgr"
done
echo "  Run an approved install dry run with SFW_VERBOSE=true; it should show the Socket Firewall banner."
echo "  Run <manager> --version; it should pass through without the banner."
